name: Frontend Continuous Deployment

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
# Environment
env:
  NODEJS_VERSION: 18.18.0
  IMAGE_REPO_NAME: dailb-project4-fe
  IMAGE_TAG: latest
  
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODEJS_VERSION}}
          
      - name: Perform a cache action to restore cache before dependency install
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: |
           npm install
           npm install eslint --save-dev

      - name: Run lint
        run: |
          npm run lint
          
  test:
    name: unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODEJS_VERSION}}
      
      - name: Perform a cache action to restore cache before dependency install
        id: cache-npm-test
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install
          npm install prettier --save-dev
  
      - name: Run test
        run: npm run test
        
  deploy:
    name: Deploy AWS
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Configure AWS Credentials for Deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login AWS
        uses: aws-actions/amazon-ecr-login@v2
        with: 
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Build and Push Docker Image
        run: |
          aws eks --region us-east-1 update-kubeconfig --name dailb-cluster
          kubectl get svc
          export EXTERNALIP=$(kubectl get svc backend -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}{"\n"}{.status.loadBalancer.ingress[0].ip}')
          echo "EXTERNALIP=$EXTERNALIP"
          docker build --build-arg REACT_APP_MOVIE_API_URL=http://$EXTERNALIP -t ${{env.IMAGE_REPO_NAME}}:${{env.IMAGE_TAG}} .
          docker tag ${{env.IMAGE_REPO_NAME}}:${{env.IMAGE_TAG}} 427645120130.dkr.ecr.us-east-1.amazonaws.com/${{env.IMAGE_REPO_NAME}}:${{env.IMAGE_TAG}}
          docker push 427645120130.dkr.ecr.us-east-1.amazonaws.com/${{env.IMAGE_REPO_NAME}}:${{env.IMAGE_TAG}}
  
      - name: Deploy to AWS EKS
        run: |
          aws eks --region us-east-1 update-kubeconfig --name dailb-cluster
          cd k8s
          kustomize edit set image frontend=427645120130.dkr.ecr.us-east-1.amazonaws.com/${{env.IMAGE_REPO_NAME}}:${{env.IMAGE_TAG}}
          kustomize build | kubectl apply -f -
  